language: clojure
lein: lein2
before_script:
- lein2 version
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: E/KeJAXi9poCB9NeNICiWh0imDCxsJ2iOB4FR6zQ+OlWcEuukKbETZXG10fO6Osh4DTfToMngLaD6+zXdTNMK+khpQzfCynv5I6dgJrviOwsxC1tjK/VVUVHJun64MZo1x6e5E/8Pj4YvmgFhkS5Nn8OfhJQ+ahEWrppsBANN60=
